# -*- coding: utf-8 -*-
"""03_카카오로컬.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0IYBN275npUTegH6ZO8Ut8kKJf2-KnY
"""

import requests
from urllib.parse import quote
import pandas as pd
import json

"""API키 가져오기"""

with open('./kakaoapi.txt') as kf:
  kakao_key = kf.read()

"""URL 만들기"""

local_url  = "https://dapi.kakao.com/v2/local/search/address.json"
addr = '광주광역시 북구 태봉로 46'
url = f'{local_url}?query={quote(addr)}'
url

#API Key를 입력하기 위한 헤더를 만들어 줌
header = {'Authorization':f'KakaoAK {kakao_key}'}

"""요청해서 결과 얻기"""

result = requests.get(url, headers=header).json()
result

result.keys()

result['documents'][0].keys()

경도 = float(result['documents'][0]['x'])
위도 = float(result['documents'][0]['y'])
도로명주소 = result['documents'][0]['address_name']


data={
    '장소':[''],
    '자동차정비업체종류':[''],
    '도로명주소':[도로명주소],
    '위도':[위도],
    '경도':[경도],
    '전화번호':['']
}
df = pd.DataFrame(data)
df.to_csv('사고지점.csv',index=False)
df

